#!/usr/bin/Rscript
library(ComplexHeatmap)
library(RColorBrewer)
library(methods)
message ("Plotting CCMPvsMCOMMODA.matrix...")
colors <- colorRampPalette(c("white", "blue", "magenta"))(n = 300)
ht_global_opt(heatmap_row_names_gp = gpar(fontsize = 8, fontface = "italic"), heatmap_column_names_gp = gpar(fontsize = 8), heatmap_column_title_gp = gpar(fontsize = 12))
pdf(file="CCMPvsMCOMMODA.matrix.pdf", useDingbats=FALSE, width=5, height=4)
CCMPvsMCOMMODA <- read.csv("CCMPvsMCOMMODA.matrix", header=TRUE)
rownames(CCMPvsMCOMMODA) <- CCMPvsMCOMMODA[,1]
colnames(CCMPvsMCOMMODA)
data_CCMPvsMCOMMODA <- data.matrix(CCMPvsMCOMMODA[,2:ncol(CCMPvsMCOMMODA)])
ht_CCMPvsMCOMMODA = Heatmap(data_CCMPvsMCOMMODA, name = "CCMPvsMCOMMODA", width = unit(51, "mm"), cluster_rows = FALSE, cluster_columns = FALSE, rect_gp = gpar(col = "white", lty = 1, lwd = 1), column_title = "CCMPvsMCOMMODAmatrix", col = colors)
class(ht_CCMPvsMCOMMODA)
draw(ht_CCMPvsMCOMMODA, heatmap_legend_side = "right")
dev.off()
