#!/usr/bin/Rscript
library(ComplexHeatmap)
library(RColorBrewer)
library(methods)
message ("Plotting MCOMMODAvsOTAURI.matrix...")
colors <- colorRampPalette(c("white", "blue", "magenta"))(n = 300)
ht_global_opt(heatmap_row_names_gp = gpar(fontsize = 8, fontface = "italic"), heatmap_column_names_gp = gpar(fontsize = 8), heatmap_column_title_gp = gpar(fontsize = 12))
pdf(file="MCOMMODAvsOTAURI.matrix.pdf", useDingbats=FALSE, width=5, height=4)
MCOMMODAvsOTAURI <- read.csv("MCOMMODAvsOTAURI.matrix", header=TRUE)
rownames(MCOMMODAvsOTAURI) <- MCOMMODAvsOTAURI[,1]
colnames(MCOMMODAvsOTAURI)
data_MCOMMODAvsOTAURI <- data.matrix(MCOMMODAvsOTAURI[,2:ncol(MCOMMODAvsOTAURI)])
ht_MCOMMODAvsOTAURI = Heatmap(data_MCOMMODAvsOTAURI, name = "MCOMMODAvsOTAURI", width = unit(66, "mm"), cluster_rows = FALSE, cluster_columns = FALSE, rect_gp = gpar(col = "white", lty = 1, lwd = 1), column_title = "MCOMMODAvsOTAURImatrix", col = colors)
class(ht_MCOMMODAvsOTAURI)
draw(ht_MCOMMODAvsOTAURI, heatmap_legend_side = "right")
dev.off()
