#!/usr/bin/Rscript
library(ComplexHeatmap)
library(RColorBrewer)
library(methods)
message ("Plotting MPUSIvsCOCCO.matrix...")
colors <- colorRampPalette(c("white", "blue", "magenta"))(n = 300)
ht_global_opt(heatmap_row_names_gp = gpar(fontsize = 8, fontface = "italic"), heatmap_column_names_gp = gpar(fontsize = 8), heatmap_column_title_gp = gpar(fontsize = 12))
pdf(file="MPUSIvsCOCCO.matrix.pdf", useDingbats=FALSE, width=6, height=4)
MPUSIvsCOCCO <- read.csv("MPUSIvsCOCCO.matrix", header=TRUE)
rownames(MPUSIvsCOCCO) <- MPUSIvsCOCCO[,1]
colnames(MPUSIvsCOCCO)
data_MPUSIvsCOCCO <- data.matrix(MPUSIvsCOCCO[,2:ncol(MPUSIvsCOCCO)])
ht_MPUSIvsCOCCO = Heatmap(data_MPUSIvsCOCCO, name = "MPUSIvsCOCCO", width = unit(87, "mm"), cluster_rows = FALSE, cluster_columns = FALSE, rect_gp = gpar(col = "white", lty = 1, lwd = 1), column_title = "MPUSIvsCOCCOmatrix", col = colors)
class(ht_MPUSIvsCOCCO)
draw(ht_MPUSIvsCOCCO, heatmap_legend_side = "right")
dev.off()
