#!/usr/bin/Rscript
library(ComplexHeatmap)
library(RColorBrewer)
library(methods)
message ("Plotting OLUCIvsOTAURI.matrix...")
colors <- colorRampPalette(c("white", "blue", "magenta"))(n = 300)
ht_global_opt(heatmap_row_names_gp = gpar(fontsize = 8, fontface = "italic"), heatmap_column_names_gp = gpar(fontsize = 8), heatmap_column_title_gp = gpar(fontsize = 12))
pdf(file="OLUCIvsOTAURI.matrix.pdf", useDingbats=FALSE, width=5, height=4)
OLUCIvsOTAURI <- read.csv("OLUCIvsOTAURI.matrix", header=TRUE)
rownames(OLUCIvsOTAURI) <- OLUCIvsOTAURI[,1]
colnames(OLUCIvsOTAURI)
data_OLUCIvsOTAURI <- data.matrix(OLUCIvsOTAURI[,2:ncol(OLUCIvsOTAURI)])
ht_OLUCIvsOTAURI = Heatmap(data_OLUCIvsOTAURI, name = "OLUCIvsOTAURI", width = unit(66, "mm"), cluster_rows = FALSE, cluster_columns = FALSE, rect_gp = gpar(col = "white", lty = 1, lwd = 1), column_title = "OLUCIvsOTAURImatrix", col = colors)
class(ht_OLUCIvsOTAURI)
draw(ht_OLUCIvsOTAURI, heatmap_legend_side = "right")
dev.off()
