#!/usr/bin/perl
## Pombert Lab, Illinois Tech, 2022
my $name = 'check_coverage.pl';
my $version = '0.1';
my $updated = '2022-11-10';

use strict;
use warnings;
use Getopt::Long qw(GetOptions);

my $usage = <<"USAGE";
NAME		${name}
VERSION		${version}
UPDATED		${updated}
SYNOPSIS	

COMMAND		check_coverage.pl \\
		  -c *.coverage \\
		  -d *.depth \\
		  -l eint_rRNA.loci \\
		  -o eint_RNA_cov.txt

OPTIONS:
-c (--cov)	Coverage file (.coverage) generated by get_SNPs.pl
-d (--dep)	Depth file (.depth) generated by get_SNPs.pl
-l (--loci)	File containing loci to check
-o (--out) Output file
USAGE
die "\n$usage\n" unless @ARGV;

my @command = @ARGV;

my $coverage_file;
my $depth_file;
my $loci_file;
my $output;
GetOptions(
	'c|cov=s' => \$coverage_file,
	'd|dep=s' => \$depth_file,
	'l|loci=s'	=> \$loci_file,
	'o|out=s' => \$output
);

open COV, '<', $coverage_file or die $!;
open DEP, '<', $depth_file or die $!;
open LOC, '<', $loci_file or die $!;
open OUT, '>', $output or die $!;

print OUT "$0 @command\n\n";

## Creating a coverage database
my %cov;
while (my $line = <COV>){
	chomp $line;
	my @data = split("\t", $line);
	my $sequence = $data[0];
	my $position = $data[1];
	my $depth = $data[2];
	$cov{$sequence}{$position} = $depth;
}
close COV;

## Getting average depth from DEPTH file
my $av_depth;
while (my $line = <DEP>){
	chomp $line;
	unless ($line =~ /^Contig\tAverage depth/){
		my @data = split("\t", $line);
		$av_depth = $data[2];
	}
}

## Working on desired loci
my $tot_sum;
my $tot_length;

while (my $line = <LOC>){
	chomp $line;
	my @data = split(':', $line);
	my $locus = $data[0];
	my ($start, $end) = split(/-/, $data[1]);
	
	my $sum = 0;
	my $length = $end - $start;
	$tot_length += $length;
	for my $pos ($start..$end){
		$sum += $cov{$locus}{$pos};
	}
	$tot_sum += $sum;

	my $average = $sum/$length;
	print OUT "Local average: $average\n";

}

my $tot_ave = $tot_sum/$tot_length;
print OUT "\nTotal average: $tot_ave\n";
print OUT "Expected average: $av_depth\n\n";
