#!/usr/bin/Rscript
library(ComplexHeatmap)
library(RColorBrewer)
library(methods)
message ("Plotting CCMPvsCOCCO.matrix...")
colors <- colorRampPalette(c("white", "blue", "magenta"))(n = 300)
ht_global_opt(heatmap_row_names_gp = gpar(fontsize = 8, fontface = "italic"), heatmap_column_names_gp = gpar(fontsize = 8), heatmap_column_title_gp = gpar(fontsize = 12))
pdf(file="CCMPvsCOCCO.matrix.pdf", useDingbats=FALSE, width=6, height=4)
CCMPvsCOCCO <- read.csv("CCMPvsCOCCO.matrix", header=TRUE)
rownames(CCMPvsCOCCO) <- CCMPvsCOCCO[,1]
colnames(CCMPvsCOCCO)
data_CCMPvsCOCCO <- data.matrix(CCMPvsCOCCO[,2:ncol(CCMPvsCOCCO)])
ht_CCMPvsCOCCO = Heatmap(data_CCMPvsCOCCO, name = "CCMPvsCOCCO", width = unit(87, "mm"), cluster_rows = FALSE, cluster_columns = FALSE, rect_gp = gpar(col = "white", lty = 1, lwd = 1), column_title = "CCMPvsCOCCOmatrix", col = colors)
class(ht_CCMPvsCOCCO)
draw(ht_CCMPvsCOCCO, heatmap_legend_side = "right")
dev.off()
