#!/usr/bin/Rscript
library(ComplexHeatmap)
library(RColorBrewer)
library(methods)
message ("Plotting COCCOvsCCMP.matrix...")
colors <- colorRampPalette(c("white", "blue", "magenta"))(n = 300)
ht_global_opt(heatmap_row_names_gp = gpar(fontsize = 8, fontface = "italic"), heatmap_column_names_gp = gpar(fontsize = 8), heatmap_column_title_gp = gpar(fontsize = 12))
pdf(file="COCCOvsCCMP.matrix.pdf", useDingbats=FALSE, width=5, height=4)
COCCOvsCCMP <- read.csv("COCCOvsCCMP.matrix", header=TRUE)
rownames(COCCOvsCCMP) <- COCCOvsCCMP[,1]
colnames(COCCOvsCCMP)
data_COCCOvsCCMP <- data.matrix(COCCOvsCCMP[,2:ncol(COCCOvsCCMP)])
ht_COCCOvsCCMP = Heatmap(data_COCCOvsCCMP, name = "COCCOvsCCMP", width = unit(60, "mm"), cluster_rows = FALSE, cluster_columns = FALSE, rect_gp = gpar(col = "white", lty = 1, lwd = 1), column_title = "COCCOvsCCMPmatrix", col = colors)
class(ht_COCCOvsCCMP)
draw(ht_COCCOvsCCMP, heatmap_legend_side = "right")
dev.off()
