#!/usr/bin/Rscript
library(ComplexHeatmap)
library(RColorBrewer)
library(methods)
message ("Plotting COCCOvsCOCCO.matrix...")
colors <- colorRampPalette(c("white", "blue", "magenta"))(n = 300)
ht_global_opt(heatmap_row_names_gp = gpar(fontsize = 8, fontface = "italic"), heatmap_column_names_gp = gpar(fontsize = 8), heatmap_column_title_gp = gpar(fontsize = 12))
pdf(file="COCCOvsCOCCO.matrix.pdf", useDingbats=FALSE, width=6, height=4)
COCCOvsCOCCO <- read.csv("COCCOvsCOCCO.matrix", header=TRUE)
rownames(COCCOvsCOCCO) <- COCCOvsCOCCO[,1]
colnames(COCCOvsCOCCO)
data_COCCOvsCOCCO <- data.matrix(COCCOvsCOCCO[,2:ncol(COCCOvsCOCCO)])
ht_COCCOvsCOCCO = Heatmap(data_COCCOvsCOCCO, name = "COCCOvsCOCCO", width = unit(87, "mm"), cluster_rows = FALSE, cluster_columns = FALSE, rect_gp = gpar(col = "white", lty = 1, lwd = 1), column_title = "COCCOvsCOCCOmatrix", col = colors)
class(ht_COCCOvsCOCCO)
draw(ht_COCCOvsCOCCO, heatmap_legend_side = "right")
dev.off()
