#!/usr/bin/Rscript
library(ComplexHeatmap)
library(RColorBrewer)
library(methods)
message ("Plotting MCOMMODAvsCCMP.matrix...")
colors <- colorRampPalette(c("white", "blue", "magenta"))(n = 300)
ht_global_opt(heatmap_row_names_gp = gpar(fontsize = 8, fontface = "italic"), heatmap_column_names_gp = gpar(fontsize = 8), heatmap_column_title_gp = gpar(fontsize = 12))
pdf(file="MCOMMODAvsCCMP.matrix.pdf", useDingbats=FALSE, width=5, height=4)
MCOMMODAvsCCMP <- read.csv("MCOMMODAvsCCMP.matrix", header=TRUE)
rownames(MCOMMODAvsCCMP) <- MCOMMODAvsCCMP[,1]
colnames(MCOMMODAvsCCMP)
data_MCOMMODAvsCCMP <- data.matrix(MCOMMODAvsCCMP[,2:ncol(MCOMMODAvsCCMP)])
ht_MCOMMODAvsCCMP = Heatmap(data_MCOMMODAvsCCMP, name = "MCOMMODAvsCCMP", width = unit(60, "mm"), cluster_rows = FALSE, cluster_columns = FALSE, rect_gp = gpar(col = "white", lty = 1, lwd = 1), column_title = "MCOMMODAvsCCMPmatrix", col = colors)
class(ht_MCOMMODAvsCCMP)
draw(ht_MCOMMODAvsCCMP, heatmap_legend_side = "right")
dev.off()
