#!/usr/bin/Rscript
library(ComplexHeatmap)
library(RColorBrewer)
library(methods)
message ("Plotting MCOMMODAvsBATHY.matrix...")
colors <- colorRampPalette(c("white", "blue", "magenta"))(n = 300)
ht_global_opt(heatmap_row_names_gp = gpar(fontsize = 8, fontface = "italic"), heatmap_column_names_gp = gpar(fontsize = 8), heatmap_column_title_gp = gpar(fontsize = 12))
pdf(file="MCOMMODAvsBATHY.matrix.pdf", useDingbats=FALSE, width=5, height=4)
MCOMMODAvsBATHY <- read.csv("MCOMMODAvsBATHY.matrix", header=TRUE)
rownames(MCOMMODAvsBATHY) <- MCOMMODAvsBATHY[,1]
colnames(MCOMMODAvsBATHY)
data_MCOMMODAvsBATHY <- data.matrix(MCOMMODAvsBATHY[,2:ncol(MCOMMODAvsBATHY)])
ht_MCOMMODAvsBATHY = Heatmap(data_MCOMMODAvsBATHY, name = "MCOMMODAvsBATHY", width = unit(57, "mm"), cluster_rows = FALSE, cluster_columns = FALSE, rect_gp = gpar(col = "white", lty = 1, lwd = 1), column_title = "MCOMMODAvsBATHYmatrix", col = colors)
class(ht_MCOMMODAvsBATHY)
draw(ht_MCOMMODAvsBATHY, heatmap_legend_side = "right")
dev.off()
