#!/usr/bin/Rscript
library(ComplexHeatmap)
library(RColorBrewer)
library(methods)
message ("Plotting MCOMMODAvsCOCCO.matrix...")
colors <- colorRampPalette(c("white", "blue", "magenta"))(n = 300)
ht_global_opt(heatmap_row_names_gp = gpar(fontsize = 8, fontface = "italic"), heatmap_column_names_gp = gpar(fontsize = 8), heatmap_column_title_gp = gpar(fontsize = 12))
pdf(file="MCOMMODAvsCOCCO.matrix.pdf", useDingbats=FALSE, width=6, height=4)
MCOMMODAvsCOCCO <- read.csv("MCOMMODAvsCOCCO.matrix", header=TRUE)
rownames(MCOMMODAvsCOCCO) <- MCOMMODAvsCOCCO[,1]
colnames(MCOMMODAvsCOCCO)
data_MCOMMODAvsCOCCO <- data.matrix(MCOMMODAvsCOCCO[,2:ncol(MCOMMODAvsCOCCO)])
ht_MCOMMODAvsCOCCO = Heatmap(data_MCOMMODAvsCOCCO, name = "MCOMMODAvsCOCCO", width = unit(87, "mm"), cluster_rows = FALSE, cluster_columns = FALSE, rect_gp = gpar(col = "white", lty = 1, lwd = 1), column_title = "MCOMMODAvsCOCCOmatrix", col = colors)
class(ht_MCOMMODAvsCOCCO)
draw(ht_MCOMMODAvsCOCCO, heatmap_legend_side = "right")
dev.off()
