#!/usr/bin/Rscript
library(ComplexHeatmap)
library(RColorBrewer)
library(methods)
message ("Plotting MCOMMODAvsOLUCI.matrix...")
colors <- colorRampPalette(c("white", "blue", "magenta"))(n = 300)
ht_global_opt(heatmap_row_names_gp = gpar(fontsize = 8, fontface = "italic"), heatmap_column_names_gp = gpar(fontsize = 8), heatmap_column_title_gp = gpar(fontsize = 12))
pdf(file="MCOMMODAvsOLUCI.matrix.pdf", useDingbats=FALSE, width=5, height=4)
MCOMMODAvsOLUCI <- read.csv("MCOMMODAvsOLUCI.matrix", header=TRUE)
rownames(MCOMMODAvsOLUCI) <- MCOMMODAvsOLUCI[,1]
colnames(MCOMMODAvsOLUCI)
data_MCOMMODAvsOLUCI <- data.matrix(MCOMMODAvsOLUCI[,2:ncol(MCOMMODAvsOLUCI)])
ht_MCOMMODAvsOLUCI = Heatmap(data_MCOMMODAvsOLUCI, name = "MCOMMODAvsOLUCI", width = unit(63, "mm"), cluster_rows = FALSE, cluster_columns = FALSE, rect_gp = gpar(col = "white", lty = 1, lwd = 1), column_title = "MCOMMODAvsOLUCImatrix", col = colors)
class(ht_MCOMMODAvsOLUCI)
draw(ht_MCOMMODAvsOLUCI, heatmap_legend_side = "right")
dev.off()
