#!/usr/bin/Rscript
library(ComplexHeatmap)
library(RColorBrewer)
library(methods)
message ("Plotting MCOMMODAvsMPUSI.matrix...")
colors <- colorRampPalette(c("white", "blue", "magenta"))(n = 300)
ht_global_opt(heatmap_row_names_gp = gpar(fontsize = 8, fontface = "italic"), heatmap_column_names_gp = gpar(fontsize = 8), heatmap_column_title_gp = gpar(fontsize = 12))
pdf(file="MCOMMODAvsMPUSI.matrix.pdf", useDingbats=FALSE, width=5, height=4)
MCOMMODAvsMPUSI <- read.csv("MCOMMODAvsMPUSI.matrix", header=TRUE)
rownames(MCOMMODAvsMPUSI) <- MCOMMODAvsMPUSI[,1]
colnames(MCOMMODAvsMPUSI)
data_MCOMMODAvsMPUSI <- data.matrix(MCOMMODAvsMPUSI[,2:ncol(MCOMMODAvsMPUSI)])
ht_MCOMMODAvsMPUSI = Heatmap(data_MCOMMODAvsMPUSI, name = "MCOMMODAvsMPUSI", width = unit(60, "mm"), cluster_rows = FALSE, cluster_columns = FALSE, rect_gp = gpar(col = "white", lty = 1, lwd = 1), column_title = "MCOMMODAvsMPUSImatrix", col = colors)
class(ht_MCOMMODAvsMPUSI)
draw(ht_MCOMMODAvsMPUSI, heatmap_legend_side = "right")
dev.off()
