#!/usr/bin/Rscript
library(ComplexHeatmap)
library(RColorBrewer)
library(methods)
message ("Plotting MCOMMODAvsMCOMMODA.matrix...")
colors <- colorRampPalette(c("white", "blue", "magenta"))(n = 300)
ht_global_opt(heatmap_row_names_gp = gpar(fontsize = 8, fontface = "italic"), heatmap_column_names_gp = gpar(fontsize = 8), heatmap_column_title_gp = gpar(fontsize = 12))
pdf(file="MCOMMODAvsMCOMMODA.matrix.pdf", useDingbats=FALSE, width=5, height=4)
MCOMMODAvsMCOMMODA <- read.csv("MCOMMODAvsMCOMMODA.matrix", header=TRUE)
rownames(MCOMMODAvsMCOMMODA) <- MCOMMODAvsMCOMMODA[,1]
colnames(MCOMMODAvsMCOMMODA)
data_MCOMMODAvsMCOMMODA <- data.matrix(MCOMMODAvsMCOMMODA[,2:ncol(MCOMMODAvsMCOMMODA)])
ht_MCOMMODAvsMCOMMODA = Heatmap(data_MCOMMODAvsMCOMMODA, name = "MCOMMODAvsMCOMMODA", width = unit(51, "mm"), cluster_rows = FALSE, cluster_columns = FALSE, rect_gp = gpar(col = "white", lty = 1, lwd = 1), column_title = "MCOMMODAvsMCOMMODAmatrix", col = colors)
class(ht_MCOMMODAvsMCOMMODA)
draw(ht_MCOMMODAvsMCOMMODA, heatmap_legend_side = "right")
dev.off()
