#!/usr/bin/Rscript
library(ComplexHeatmap)
library(RColorBrewer)
library(methods)
message ("Plotting MPUSIvsCCMP.matrix...")
colors <- colorRampPalette(c("white", "blue", "magenta"))(n = 300)
ht_global_opt(heatmap_row_names_gp = gpar(fontsize = 8, fontface = "italic"), heatmap_column_names_gp = gpar(fontsize = 8), heatmap_column_title_gp = gpar(fontsize = 12))
pdf(file="MPUSIvsCCMP.matrix.pdf", useDingbats=FALSE, width=5, height=4)
MPUSIvsCCMP <- read.csv("MPUSIvsCCMP.matrix", header=TRUE)
rownames(MPUSIvsCCMP) <- MPUSIvsCCMP[,1]
colnames(MPUSIvsCCMP)
data_MPUSIvsCCMP <- data.matrix(MPUSIvsCCMP[,2:ncol(MPUSIvsCCMP)])
ht_MPUSIvsCCMP = Heatmap(data_MPUSIvsCCMP, name = "MPUSIvsCCMP", width = unit(60, "mm"), cluster_rows = FALSE, cluster_columns = FALSE, rect_gp = gpar(col = "white", lty = 1, lwd = 1), column_title = "MPUSIvsCCMPmatrix", col = colors)
class(ht_MPUSIvsCCMP)
draw(ht_MPUSIvsCCMP, heatmap_legend_side = "right")
dev.off()
