#!/usr/bin/Rscript
library(ComplexHeatmap)
library(RColorBrewer)
library(methods)
message ("Plotting MPUSIvsMPUSI.matrix...")
colors <- colorRampPalette(c("white", "blue", "magenta"))(n = 300)
ht_global_opt(heatmap_row_names_gp = gpar(fontsize = 8, fontface = "italic"), heatmap_column_names_gp = gpar(fontsize = 8), heatmap_column_title_gp = gpar(fontsize = 12))
pdf(file="MPUSIvsMPUSI.matrix.pdf", useDingbats=FALSE, width=5, height=4)
MPUSIvsMPUSI <- read.csv("MPUSIvsMPUSI.matrix", header=TRUE)
rownames(MPUSIvsMPUSI) <- MPUSIvsMPUSI[,1]
colnames(MPUSIvsMPUSI)
data_MPUSIvsMPUSI <- data.matrix(MPUSIvsMPUSI[,2:ncol(MPUSIvsMPUSI)])
ht_MPUSIvsMPUSI = Heatmap(data_MPUSIvsMPUSI, name = "MPUSIvsMPUSI", width = unit(60, "mm"), cluster_rows = FALSE, cluster_columns = FALSE, rect_gp = gpar(col = "white", lty = 1, lwd = 1), column_title = "MPUSIvsMPUSImatrix", col = colors)
class(ht_MPUSIvsMPUSI)
draw(ht_MPUSIvsMPUSI, heatmap_legend_side = "right")
dev.off()
