#!/usr/bin/Rscript
library(ComplexHeatmap)
library(RColorBrewer)
library(methods)
message ("Plotting MPUSIvsBATHY.matrix...")
colors <- colorRampPalette(c("white", "blue", "magenta"))(n = 300)
ht_global_opt(heatmap_row_names_gp = gpar(fontsize = 8, fontface = "italic"), heatmap_column_names_gp = gpar(fontsize = 8), heatmap_column_title_gp = gpar(fontsize = 12))
pdf(file="MPUSIvsBATHY.matrix.pdf", useDingbats=FALSE, width=5, height=4)
MPUSIvsBATHY <- read.csv("MPUSIvsBATHY.matrix", header=TRUE)
rownames(MPUSIvsBATHY) <- MPUSIvsBATHY[,1]
colnames(MPUSIvsBATHY)
data_MPUSIvsBATHY <- data.matrix(MPUSIvsBATHY[,2:ncol(MPUSIvsBATHY)])
ht_MPUSIvsBATHY = Heatmap(data_MPUSIvsBATHY, name = "MPUSIvsBATHY", width = unit(57, "mm"), cluster_rows = FALSE, cluster_columns = FALSE, rect_gp = gpar(col = "white", lty = 1, lwd = 1), column_title = "MPUSIvsBATHYmatrix", col = colors)
class(ht_MPUSIvsBATHY)
draw(ht_MPUSIvsBATHY, heatmap_legend_side = "right")
dev.off()
