#!/usr/bin/Rscript
library(ComplexHeatmap)
library(RColorBrewer)
library(methods)
message ("Plotting MPUSIvsOTAURI.matrix...")
colors <- colorRampPalette(c("white", "blue", "magenta"))(n = 300)
ht_global_opt(heatmap_row_names_gp = gpar(fontsize = 8, fontface = "italic"), heatmap_column_names_gp = gpar(fontsize = 8), heatmap_column_title_gp = gpar(fontsize = 12))
pdf(file="MPUSIvsOTAURI.matrix.pdf", useDingbats=FALSE, width=5, height=4)
MPUSIvsOTAURI <- read.csv("MPUSIvsOTAURI.matrix", header=TRUE)
rownames(MPUSIvsOTAURI) <- MPUSIvsOTAURI[,1]
colnames(MPUSIvsOTAURI)
data_MPUSIvsOTAURI <- data.matrix(MPUSIvsOTAURI[,2:ncol(MPUSIvsOTAURI)])
ht_MPUSIvsOTAURI = Heatmap(data_MPUSIvsOTAURI, name = "MPUSIvsOTAURI", width = unit(66, "mm"), cluster_rows = FALSE, cluster_columns = FALSE, rect_gp = gpar(col = "white", lty = 1, lwd = 1), column_title = "MPUSIvsOTAURImatrix", col = colors)
class(ht_MPUSIvsOTAURI)
draw(ht_MPUSIvsOTAURI, heatmap_legend_side = "right")
dev.off()
