#!/usr/bin/Rscript
library(ComplexHeatmap)
library(RColorBrewer)
library(methods)
message ("Plotting OLUCIvsMCOMMODA.matrix...")
colors <- colorRampPalette(c("white", "blue", "magenta"))(n = 300)
ht_global_opt(heatmap_row_names_gp = gpar(fontsize = 8, fontface = "italic"), heatmap_column_names_gp = gpar(fontsize = 8), heatmap_column_title_gp = gpar(fontsize = 12))
pdf(file="OLUCIvsMCOMMODA.matrix.pdf", useDingbats=FALSE, width=5, height=4)
OLUCIvsMCOMMODA <- read.csv("OLUCIvsMCOMMODA.matrix", header=TRUE)
rownames(OLUCIvsMCOMMODA) <- OLUCIvsMCOMMODA[,1]
colnames(OLUCIvsMCOMMODA)
data_OLUCIvsMCOMMODA <- data.matrix(OLUCIvsMCOMMODA[,2:ncol(OLUCIvsMCOMMODA)])
ht_OLUCIvsMCOMMODA = Heatmap(data_OLUCIvsMCOMMODA, name = "OLUCIvsMCOMMODA", width = unit(51, "mm"), cluster_rows = FALSE, cluster_columns = FALSE, rect_gp = gpar(col = "white", lty = 1, lwd = 1), column_title = "OLUCIvsMCOMMODAmatrix", col = colors)
class(ht_OLUCIvsMCOMMODA)
draw(ht_OLUCIvsMCOMMODA, heatmap_legend_side = "right")
dev.off()
