#!/usr/bin/Rscript
library(ComplexHeatmap)
library(RColorBrewer)
library(methods)
message ("Plotting OLUCIvsCCMP.matrix...")
colors <- colorRampPalette(c("white", "blue", "magenta"))(n = 300)
ht_global_opt(heatmap_row_names_gp = gpar(fontsize = 8, fontface = "italic"), heatmap_column_names_gp = gpar(fontsize = 8), heatmap_column_title_gp = gpar(fontsize = 12))
pdf(file="OLUCIvsCCMP.matrix.pdf", useDingbats=FALSE, width=5, height=4)
OLUCIvsCCMP <- read.csv("OLUCIvsCCMP.matrix", header=TRUE)
rownames(OLUCIvsCCMP) <- OLUCIvsCCMP[,1]
colnames(OLUCIvsCCMP)
data_OLUCIvsCCMP <- data.matrix(OLUCIvsCCMP[,2:ncol(OLUCIvsCCMP)])
ht_OLUCIvsCCMP = Heatmap(data_OLUCIvsCCMP, name = "OLUCIvsCCMP", width = unit(60, "mm"), cluster_rows = FALSE, cluster_columns = FALSE, rect_gp = gpar(col = "white", lty = 1, lwd = 1), column_title = "OLUCIvsCCMPmatrix", col = colors)
class(ht_OLUCIvsCCMP)
draw(ht_OLUCIvsCCMP, heatmap_legend_side = "right")
dev.off()
