#!/usr/bin/Rscript
library(ComplexHeatmap)
library(RColorBrewer)
library(methods)
message ("Plotting OTAURIvsCOCCO.matrix...")
colors <- colorRampPalette(c("white", "blue", "magenta"))(n = 300)
ht_global_opt(heatmap_row_names_gp = gpar(fontsize = 8, fontface = "italic"), heatmap_column_names_gp = gpar(fontsize = 8), heatmap_column_title_gp = gpar(fontsize = 12))
pdf(file="OTAURIvsCOCCO.matrix.pdf", useDingbats=FALSE, width=6, height=4)
OTAURIvsCOCCO <- read.csv("OTAURIvsCOCCO.matrix", header=TRUE)
rownames(OTAURIvsCOCCO) <- OTAURIvsCOCCO[,1]
colnames(OTAURIvsCOCCO)
data_OTAURIvsCOCCO <- data.matrix(OTAURIvsCOCCO[,2:ncol(OTAURIvsCOCCO)])
ht_OTAURIvsCOCCO = Heatmap(data_OTAURIvsCOCCO, name = "OTAURIvsCOCCO", width = unit(87, "mm"), cluster_rows = FALSE, cluster_columns = FALSE, rect_gp = gpar(col = "white", lty = 1, lwd = 1), column_title = "OTAURIvsCOCCOmatrix", col = colors)
class(ht_OTAURIvsCOCCO)
draw(ht_OTAURIvsCOCCO, heatmap_legend_side = "right")
dev.off()
