#!/usr/bin/env python3

name = "assign_chromosome_number.py"
version = "0.2.0"
updated = "2025-08-12"

from sys import argv
from argparse import ArgumentParser
from os import makedirs
from os.path import isdir,basename
from textwrap import wrap

############################################################
## Readme
############################################################

usage = f"""
NAME        {name}
VERSION     {version}
UPDATED     {updated}
SYNOPSIS    Utilizes chromosome map generated by orient_fastas_to_reference.py to homogenize naming between the reference
            and the new assembly.

USAGE       {name} \\
              -m all.map \\
              -f 50507.oriented.fasta \\
              -o 50507

OPTIONS
-m (--map)      Chromosome map file
-f (--fasta)    Assembly FASTA file
-o (--outdir)   Output directory [Default = CHROMOSOME_ASSIGNMENT]
"""

if len(argv) < 2:
    print(usage)
    exit()

############################################################
## Command lines arguments
############################################################

GetOptions = ArgumentParser()

GetOptions.add_argument("-m","--map",required=True)
GetOptions.add_argument("-f","--fasta",required=True)
GetOptions.add_argument("-o","--outdir",default="CHROMOSOME_ASSIGNMENT")

args = GetOptions.parse_args()

map_file = args.map
fasta_file = args.fasta
outdir = args.outdir

if not isdir(outdir):
    makedirs(outdir,mode=0o755)

filename = basename(fasta_file).split(".")[0]

############################################################
## Read fasta file
############################################################

FASTA = open(fasta_file,'r')

locus = ""
contigs = {}

for line in FASTA:

    line = line.strip()

    if line == "":
        continue

    ## Read fasta header
    if line[0] == ">":

        locus = line[1:]
        contigs[locus] = ""
        continue

    contigs[locus] += line

FASTA.close()

############################################################
## Read chromosome mapping file
############################################################

MAP = open(map_file,'r')

mappings = {}
mapped_to = ""

for line in MAP:

    line = line.strip()
    
    if line == "":
        continue

    if line[0:2] == ">>":
    
        mapped_to = line[2:].split("\t")[0]
        mappings[mapped_to] = []
        continue
    
    if line[0] == ">":

        mapped,type = line[1:].split("\t")[0:2]

        if type != "Primary":
            continue

        mappings[mapped_to].append(mapped)

        continue

MAP.close()

ASSIGNED_FASTA = open(f"{outdir}/{filename}.assigned.fasta",'w')
ASSIGNMENTS = open(f"{outdir}/{filename}.chromosome_assignments",'w')

############################################################
## Assign chromosome to arbitrary contigs
############################################################

## Iterate over chromsome:contig mappings
for chromosome in sorted(mappings.keys()):

    ## Iterate over all contigs that mapped to a chromosome
    for index,contig in enumerate(mappings[chromosome]):

        ASSIGNED_FASTA.write(f">{chromosome}s{index+1}\n")
        
        ## Wrap contig sequence at 60 character length
        sequence = "\n".join(wrap(contigs[contig],60))

        ASSIGNED_FASTA.write(f"{sequence}\n")
        ASSIGNMENTS.write(f"{contig} => {chromosome}s{index+1}\n")

ASSIGNED_FASTA.close()
ASSIGNMENTS.close()